version: "3.3"

services:
  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - ./data/minio:/data/minio
    build:
      context: .
      dockerfile: minio.dockerfile
    command: minio server /data/minio --console-address ":9001"
